addons:
  code_climate:
    repo_token: a7df4df80459fdf576888307853f5dafa9547489cab338c175386c53a790c60a

language: php

php:
    5.5
    5.6
    hhvm

before_script:
    - composer install --dev --prefer-source

after_script:
  - vendor/bin/test-reporter